apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-deployment
  labels:
    app: frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
        - name: frontend
          image: yashanandd/meetflow-frontend:v1.0.0
          ports:
            - containerPort: 5173
          envFrom:
            - configMapRef:
                name: meetflow-config
